### ISSUE TITLE
Function names and headers disagree

### ISSUE THREAD

**Issue by HenriqueMatulis** [dilevin/CSC2549-a2-mass-spring-3d#10]
In the following cases, the function names suggest returning dV, but the comments suggest returning a force vector:

https://github.com/dilevin/CSC2549-a2-mass-spring-3d/blob/b1c6447986a58f45b41196aef46b3ab5f231e25d/include/dV_gravity_particle_dq.h#L7-L8

https://github.com/dilevin/CSC2549-a2-mass-spring-3d/blob/b1c6447986a58f45b41196aef46b3ab5f231e25d/include/dV_spring_particle_particle_dq.h#L10-L11

**Comment by dilevin** [comment]
the comments are always wrong
