### ISSUE TITLE
Derivate of Potential Energy 

### ISSUE THREAD

**Issue by qiongsiwu** [dilevin/CSC2549-a2-mass-spring-3d#3]
When the README is taking the derivative of the potential energey, we have

```
and now we can take derivatives of this in order to compute, say the forces. Let's see what happens if we compute the gradient of this energy with respect to the generalized coordinates. Then we get

$$\frac{\partial V\left(\mathbf{q}\right)}{\partial \mathbf{q}} = \sum_{i=0}^{m-1}S_i^T\frac{\partial V_i\left(S_i\mathbf{q}\right)}{\partial \mathbf{q}},$$
```

After pulling out S_i^T, do we still need S^i inside \frac{\partial V_i\left(S_i\mathbf{q}\right)}{\partial \mathbf{q}}?

**Comment by dilevin** [comment]
Yes you still need it. But remember that S*q is just a stand in for [q0, q1]^T. 

Its still inside the bracket to indicate that the function us till a function of the selected q's.

**Comment by qiongsiwu** [comment]
Now I see it! Thanks for the explanation!

**Comment by dilevin** [comment]
i'm going to leave this open so other can see the explanation :)
