### ISSUE TITLE
Gravity forces in assembly

### ISSUE THREAD

**Issue by abhimadan** [dilevin/CSC2549-a2-mass-spring-3d#4]
There's no `g` parameter in `assemble_forces` or `assemble_stiffness`, so we can't use it to add gravity's contribution to the assembled force vector or Hessian. Are we expected to hardcode the standard acceleration into the appropriate functions?

**Comment by dilevin** [comment]
For this assignment your bunny should be in zero g (no gravity) so you can ignore the gravity force during assembly.  You should still implement gravitational potential energy and the gradient so we can check the formulas though.
