### ISSUE TITLE
Dimensions of P matrix for boundary conditions

### ISSUE THREAD

**Issue by abhimadan** [dilevin/CSC2549-a2-mass-spring-3d#5]
In `fixed_point_constraints.h`, there's the following comment:
https://github.com/dilevin/CSC2549-a2-mass-spring-3d/blob/98ace994179a8a3ba0459ffafdd20f58c0ecd74e/include/fixed_point_constraints.h#L11

However, in `main.cpp`, P is initialized like so:
https://github.com/dilevin/CSC2549-a2-mass-spring-3d/blob/98ace994179a8a3ba0459ffafdd20f58c0ecd74e/main.cpp#L127

And then, in the readme, it says the following:
<img width="915" alt="Screen Shot 2019-09-29 at 10 12 41 PM" src="https://user-images.githubusercontent.com/7970201/65844962-49dc6400-e306-11e9-8d1e-b0cbff8b5347.png">

So the documentation variously gives the dimensions as m x n, n x n, or n x m. Based on the way it's used in main.cpp, only the first two options are viable, but which one are we supposed to implement?

**Comment by dilevin** [comment]
The README.md is wrong. It's missing a transpose (I think the notes are correct in this regard).

P is mxn where n is the number of scalar degrees-of-freedom (3*num vertices). 

As an side m=n when there are no constraints so nxn is a special case of mxn.

**Comment by dilevin** [comment]
I've updated the README.md and the README.html so everything should be correct now.

**Comment by abhimadan** [comment]
Thanks!
