### ISSUE TITLE
How to take the derivative in respective to a vector?

### ISSUE THREAD

**Issue by JerryJiehanWang** [dilevin/CSC2549-a2-mass-spring-3d#8]
For example, how to take the derivative in respective to q here:
<img width="262" alt="Screen Shot 2019-10-01 at 10 51 16 AM" src="https://user-images.githubusercontent.com/33852873/65973655-b015d380-e439-11e9-9ba8-ae84755a718c.png">

**Comment by chxie-nv** [comment]
There are many resources for Vector Calculus.
This is what I referenced to derive the gradient and Hessian:
https://en.wikipedia.org/wiki/Vector_calculus_identities

**Comment by kevincxie** [comment]
A lot of the rules are just slight modifications from single variable calculus.
I derived the gradient and Hessian referencing: https://en.wikipedia.org/wiki/Vector_calculus_identities and
https://math.stackexchange.com/questions/189434/derivative-of-quadratic-form/189436

**Comment by dilevin** [comment]
This is my favorite e-desk reference [https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf)

All these derivatives involve using the chain rule. An important concept is to keep track of which terms in the chain rule just involve scalars and which involve vectors.
